// src/autopilot/interactions/controls.ts
/** Documented registry of every interactive control id; the drift guard asserts each has
 *  an INTERACTIONS entry. Filled in per-domain by later tasks (mirrors UNTESTED_CHANNELS). */
export const INTERACTIVE_CONTROLS = new Set<string>([
  'toolbar.addressBar',
  'toolbar.back',
  'toolbar.forward',
  'toolbar.reload',
  'toolbar.home',
  'toolbar.bookmarkStar',
  'toolbar.picker',
  'shieldPopover.toggleAdblock',
  'shieldPopover.allowlistSite',
  'shieldPopover.badgeReflectsBlockedCount',
  // Task 4: tabs + keyboard shortcuts
  'tabs.newButton',
  'tabs.activate',
  'tabs.close',
  'tabs.setPinned',
  'keyboard.newTab',
  'keyboard.closeTab',
  'keyboard.reopenTab',
  // Task 11: private tab affordances
  'tabs.newPrivateButton',
  'keyboard.newPrivateTab',
  // Task 5: favorites bar/manager + sidebar history
  'favbar.openFavorite',
  'favManager.add',
  'favManager.rename',
  'favManager.delete',
  'sidebar.history.openEntry',
  'sidebar.history.deleteEntry',
  'sidebar.history.search',
  'sidebar.history.clear',
  // Task 6: sidebar saved + tags
  'sidebar.saved.openEntry',
  'sidebar.saved.delete',
  'sidebar.saved.addTag',
  'sidebar.saved.renameTag',
  'sidebar.saved.deleteTag',
  'sidebar.saved.filterByTag',
  // Task 7: settings (every tab)
  'settings.appearance.primaryColor',
  'settings.appearance.themeMode',
  'settings.search.addEngine',
  'settings.search.setDefault',
  'settings.home.homeUrl',
  'settings.tabs.idleTimeout',
  'settings.filterLists.toggleSub',
  'settings.filterLists.addList',
  'settings.filterLists.removeList',
  'settings.filterLists.updateAll',
  'settings.myFilters.save',
  'settings.allowlist.remove',
  'settings.allowlist.clearAll',
  'settings.downloads.saveDir',
  'settings.downloads.useDefault',
  'settings.sitePermissions.revoke',
  'settings.sitePermissions.clearAll',
  'settings.security.httpsOnly',
  'settings.security.webrtcPolicy',
  'settings.sync.setServerUrl',
  'settings.sync.testConnection',
  'settings.sync.startNew',
  'settings.sync.restorePhrase',
  'settings.data.export',
  'settings.data.import',
  'settings.data.importMode',
  // Task 8: overlays
  'downloads.clear',
  'confirm.confirm',
  'confirm.cancel',
  'errorOverlay.retry',
  'crashOverlay.reload',
  'safety.proceed',
  'safety.back',
  'permission.allow',
  'permission.deny',
  'redirectBar.openAnyway',
  'redirectBar.dismiss',
  // Task 9: edge/error inputs + state combinations
  'edge.addressBar.empty',
  'edge.addressBar.malformed',
  'edge.favorite.duplicate',
  'edge.tag.whitespace',
  'edge.bookmark.doubleClick',
  'combo.settingsOverSidebar',
  'combo.tabSwitchWithModal',
  // Task 9: find-in-page
  'find.open',
  'find.type',
  'find.next',
  'find.prev',
  'find.close',
  // Task 11: page zoom (ZoomIndicator popover)
  'toolbar.zoom.label',
  'toolbar.zoom.in',
  'toolbar.zoom.out',
  'toolbar.zoom.reset',
  // Task 11: page zoom (keyboard path — App.tsx window keydown)
  'toolbar.zoom.keyboard',
  // Task 10: mobile-only controls (MobileBottomBar, MobileMenuSheet, MobileTabSwitcher, MobileTopBar)
  // These are exercised in the mobile interaction tour (interactions.mobile.test.tsx).
  // They are NOT reachable in the desktop shell and NOT in the live autopilot run
  // (the live autopilot drives the desktop shell only).
  'mobile.bottomBar.saved',
  'mobile.bottomBar.history',
  'mobile.bottomBar.tabs',
  'mobile.bottomBar.menu',
  'mobile.menu.back',
  'mobile.menu.forward',
  'mobile.menu.home',
  'mobile.menu.bookmark',
  'mobile.menu.downloads',
  'mobile.menu.settings',
  'mobile.menu.find',
  'mobile.menu.zoomIn',
  'mobile.menu.zoomOut',
  'mobile.menu.zoomReset',
  'mobile.tabSwitcher.newTab',
  'mobile.tabSwitcher.newPrivateTab',
  'mobile.tabSwitcher.switch',
  'mobile.tabSwitcher.close',
  'mobile.topBar.hideToolbar',
  // Task 7 (vault): Passwords settings tab controls
  'vault.create.submit',
  'vault.unlock.submit',
  'vault.add.submit',
  'vault.search.input',
  'vault.row.showPassword',
  'vault.row.copyPassword',
  'vault.row.delete',
  'vault.lock',
]);
