// Pure logic for the coverage ratchet. No I/O, no process.exit — see
// `coverage-ratchet.mjs` for the CLI wrapper. Same split as `auditCheck.mjs` /
// `check-npm-audit.mjs`, so this is unit-testable without spawning anything.
//
// The gate is a RATCHET, not a threshold. It enforces three things:
//   1. current >= baseline          (coverage may not fall)
//   2. baseline not lowered vs HEAD (you may not relax the bar to hide a fall)
//   3. no metric file silently added/excluded (the file list is itself compared)
//
// (3) matters as much as (1): a one-line `coverage.exclude` addition would
// otherwise raise every percentage and sail through the gate.

/** The four metrics we gate on.
 *
 * `branchesTrue` is deliberately absent: it is a v8-provider artefact with
 * `total: 0` / `pct: 100`, so comparing it is comparing nothing. */
export const METRICS = ['lines', 'statements', 'functions', 'branches'];

/**
 * Compare two coverage records for one metric using exact integer arithmetic
 * (`a.covered * b.total < b.covered * a.total` means `a` covers proportionally
 * less than `b`).
 *
 * Integer cross-multiplication rather than float `pct` comparison on purpose:
 * the JSON carries exact counts, and two runs of an unchanged tree can land on
 * values that differ in the last float digit. A float compare would fail the
 * build on a rounding artefact.
 */
export function coversLess(a, b) {
  if (!a || !b) return true;
  if (a.total === 0 && b.total === 0) return false;
  if (a.total === 0) return true;
  if (b.total === 0) return false;
  return a.covered * b.total < b.covered * a.total;
}

/**
 * `undefined` for total 0 so a metric with nothing to measure is not gated.
 *
 * Truncates rather than rounds, because that is what istanbul does — and a
 * baseline that printed `75.23` next to the report's own `75.22` would be a
 * number nobody could reconcile. Gate decisions never use this: they use the
 * exact integer comparison in `coversLess`.
 */
export function pctOf(record) {
  if (!record || record.total === 0) return undefined;
  if (typeof record.pct === 'number') return record.pct;
  return Number(((record.covered / record.total) * 100).toFixed(2));
}

/**
 * Turn a `coverage-summary.json` (istanbul shape: `{ total, 'src/a.ts': … }`)
 * into the committed baseline shape. Absolute paths from the v8 provider are
 * rewritten to repo-relative so the file is stable across machines and checkouts.
 */
export function buildBaseline(summary, { repoRoot = '', vitestVersion = null } = {}) {
  if (!summary || typeof summary !== 'object') {
    throw new TypeError('buildBaseline: summary must be an object');
  }
  if (!summary.total) throw new TypeError('buildBaseline: summary has no `total`');

  const pick = (rec) => ({ total: rec.total, covered: rec.covered, pct: pctOf(rec) });

  const files = {};
  for (const [key, rec] of Object.entries(summary)) {
    if (key === 'total' || !rec) continue;
    let rel = key;
    if (repoRoot && rel.startsWith(repoRoot)) rel = rel.slice(repoRoot.length).replace(/^\//, '');
    files[rel] = {
      lines: pick(rec.lines),
      statements: pick(rec.statements),
      functions: pick(rec.functions),
      branches: pick(rec.branches),
    };
  }

  const total = {};
  for (const m of METRICS) total[m] = pick(summary.total[m]);

  return {
    $comment:
      'Generated by scripts/coverage-baseline.mjs — do not hand-edit. ' +
      'Enforced by scripts/coverage-ratchet.mjs as a ratchet: coverage may rise, ' +
      'never fall, and this file may never be lowered in the same commit.',
    vitestVersion,
    total,
    files,
  };
}

/**
 * Compare a freshly measured summary against the committed baseline.
 * Returns `{ regressions, improvements, newFiles, removedFiles }`, all arrays of
 * human-readable strings, so the caller can print them verbatim.
 */
export function compareToBaseline(baseline, current) {
  const regressions = [];
  const improvements = [];

  for (const m of METRICS) {
    const base = baseline?.total?.[m];
    const cur = current?.total?.[m];
    if (!base) {
      regressions.push(`${m}: baseline has no recorded value — regenerate the baseline`);
      continue;
    }
    if (!cur) {
      regressions.push(`${m}: current run reported no value`);
      continue;
    }
    if (coversLess(cur, base)) {
      regressions.push(
        `total ${m}: ${pctOf(cur)}% (${cur.covered}/${cur.total}) ` +
          `< baseline ${pctOf(base)}% (${base.covered}/${base.total})`,
      );
    } else if (coversLess(base, cur)) {
      improvements.push(
        `total ${m}: ${pctOf(cur)}% (${cur.covered}/${cur.total}) ` +
          `> baseline ${pctOf(base)}% (${base.covered}/${base.total})`,
      );
    }
  }

  // The file list is gated too, so a new `coverage.exclude` entry cannot be used
  // to make the numbers look better.
  const baseFiles = Object.keys(baseline?.files ?? {});
  const curFiles = Object.keys(current?.files ?? {});
  const newFiles = curFiles.filter((f) => !baseFiles.includes(f)).sort();
  const removedFiles = baseFiles.filter((f) => !curFiles.includes(f)).sort();

  for (const f of removedFiles) {
    regressions.push(
      `file dropped out of the report: ${f} — a baseline file stopped being measured. ` +
        `Restore it to coverage.include or delete it from the baseline on purpose.`,
    );
  }

  return { regressions, improvements, newFiles, removedFiles };
}

/**
 * Has the baseline been lowered relative to the committed (HEAD) version?
 * `committed` is the baseline as it exists in git; `working` is the file on disk.
 * Returns an array of lowered-metric strings (empty when nothing was lowered).
 */
export function detectBaselineLowering(committed, working) {
  const lowered = [];
  if (!committed) return lowered; // first commit that introduces a baseline
  for (const m of METRICS) {
    const c = committed?.total?.[m];
    const w = working?.total?.[m];
    if (!c || !w) continue;
    if (coversLess(w, c)) {
      lowered.push(
        `${m}: baseline ${pctOf(c)}% -> ${pctOf(w)}% ` +
          `(${c.covered}/${c.total} -> ${w.covered}/${w.total})`,
      );
    }
  }
  return lowered;
}
