// Pure logic for the coverage ratchet. No I/O, no process.exit — see
// `coverage-ratchet.mjs` for the CLI wrapper. Same split as `auditCheck.mjs` /
// `check-npm-audit.mjs`, so this is unit-testable without spawning anything.
//
// The gate is a RATCHET, not a threshold. It enforces three things:
//   1. current >= baseline          (coverage may not fall)
//   2. baseline not lowered vs the commit being tested (you may not relax the
//      bar to hide a fall)
//   3. no metric file silently added/excluded (the file list is itself compared)
//
// (3) matters as much as (1): a one-line `coverage.exclude` addition would
// otherwise raise every percentage and sail through the gate.

/** The four metrics we gate on.
 *
 * `branchesTrue` is deliberately absent: it is a v8-provider artefact with
 * `total: 0` / `pct: 100`, so comparing it is comparing nothing. */
export const METRICS = ['lines', 'statements', 'functions', 'branches'];

/**
 * Compare two coverage records for one metric using exact integer arithmetic
 * (`a.covered * b.total < b.covered * a.total` means `a` covers proportionally
 * less than `b`).
 *
 * Integer cross-multiplication rather than float `pct` comparison on purpose:
 * the JSON carries exact counts, and two runs of an unchanged tree can land on
 * values that differ in the last float digit. A float compare would fail the
 * build on a rounding artefact.
 */
export function coversLess(a, b) {
  if (!a || !b) return true;
  if (a.total === 0 && b.total === 0) return false;
  if (a.total === 0) return true;
  if (b.total === 0) return false;
  return a.covered * b.total < b.covered * a.total;
}

/**
 * `undefined` for total 0 so a metric with nothing to measure is not gated.
 *
 * Truncates rather than rounds, because that is what istanbul does — and a
 * baseline that printed `75.23` next to the report's own `75.22` would be a
 * number nobody could reconcile. Gate decisions never use this: they use the
 * exact integer comparison in `coversLess`.
 */
export function pctOf(record) {
  if (!record || record.total === 0) return undefined;
  if (typeof record.pct === 'number') return record.pct;
  return Number(((record.covered / record.total) * 100).toFixed(2));
}

/**
 * Turn a `coverage-summary.json` (istanbul shape: `{ total, 'src/a.ts': … }`)
 * into the committed baseline shape. Absolute paths from the v8 provider are
 * rewritten to repo-relative so the file is stable across machines and checkouts.
 */
export function buildBaseline(summary, { repoRoot = '', vitestVersion = null } = {}) {
  if (!summary || typeof summary !== 'object') {
    throw new TypeError('buildBaseline: summary must be an object');
  }
  if (!summary.total) throw new TypeError('buildBaseline: summary has no `total`');

  const pick = (rec) => ({ total: rec.total, covered: rec.covered, pct: pctOf(rec) });

  const files = {};
  for (const [key, rec] of Object.entries(summary)) {
    if (key === 'total' || !rec) continue;
    let rel = key;
    if (repoRoot && rel.startsWith(repoRoot)) rel = rel.slice(repoRoot.length).replace(/^\//, '');
    files[rel] = {
      lines: pick(rec.lines),
      statements: pick(rec.statements),
      functions: pick(rec.functions),
      branches: pick(rec.branches),
    };
  }

  const total = {};
  for (const m of METRICS) total[m] = pick(summary.total[m]);

  return {
    $comment:
      'Generated by scripts/coverage-baseline.mjs — do not hand-edit. ' +
      'Enforced by scripts/coverage-ratchet.mjs as a ratchet: coverage may rise, ' +
      'never fall, and this file may never be lowered in the same commit.',
    vitestVersion,
    total,
    files,
  };
}

/**
 * Compare a freshly measured summary against the committed baseline.
 * Returns `{ regressions, improvements, newFiles, removedFiles }`, all arrays of
 * human-readable strings, so the caller can print them verbatim.
 */
export function compareToBaseline(baseline, current) {
  const regressions = [];
  const improvements = [];

  for (const m of METRICS) {
    const base = baseline?.total?.[m];
    const cur = current?.total?.[m];
    if (!base) {
      regressions.push(`${m}: baseline has no recorded value — regenerate the baseline`);
      continue;
    }
    if (!cur) {
      regressions.push(`${m}: current run reported no value`);
      continue;
    }
    if (coversLess(cur, base)) {
      regressions.push(
        `total ${m}: ${pctOf(cur)}% (${cur.covered}/${cur.total}) ` +
          `< baseline ${pctOf(base)}% (${base.covered}/${base.total})`,
      );
    } else if (coversLess(base, cur)) {
      improvements.push(
        `total ${m}: ${pctOf(cur)}% (${cur.covered}/${cur.total}) ` +
          `> baseline ${pctOf(base)}% (${base.covered}/${base.total})`,
      );
    }
  }

  // The file list is gated too, so a new `coverage.exclude` entry cannot be used
  // to make the numbers look better.
  const baseFiles = Object.keys(baseline?.files ?? {});
  const curFiles = Object.keys(current?.files ?? {});
  const newFiles = curFiles.filter((f) => !baseFiles.includes(f)).sort();
  const removedFiles = baseFiles.filter((f) => !curFiles.includes(f)).sort();

  for (const f of removedFiles) {
    regressions.push(
      `file dropped out of the report: ${f} — a baseline file stopped being measured. ` +
        `Restore it to coverage.include or delete it from the baseline on purpose.`,
    );
  }

  return { regressions, improvements, newFiles, removedFiles };
}

/**
 * Has the baseline been lowered relative to the committed version at some other
 * commit? `committed` is the baseline as that commit recorded it; `working` is
 * the file on disk. Returns an array of lowered-metric strings (empty when
 * nothing was lowered, and when `committed` is null — the commit that first
 * introduced the baseline has nothing to compare against).
 */
export function detectBaselineLowering(committed, working) {
  const lowered = [];
  if (!committed) return lowered; // first commit that introduces a baseline
  for (const m of METRICS) {
    const c = committed?.total?.[m];
    const w = working?.total?.[m];
    if (!c || !w) continue;
    if (coversLess(w, c)) {
      lowered.push(
        `${m}: baseline ${pctOf(c)}% -> ${pctOf(w)}% ` +
          `(${c.covered}/${c.total} -> ${w.covered}/${w.total})`,
      );
    }
  }
  return lowered;
}

/**
 * Which commit's copy of the baseline is the "committed" one that the lowering
 * check compares the file on disk against?
 *
 * WHY THIS IS NOT `HEAD`. It used to be, and that made the check unreachable in
 * CI. A CI worktree IS the checked-out commit, so `git show HEAD:…` returned the
 * very file being checked, `detectBaselineLowering` compared it with itself, and
 * `COVERAGE_ALLOW_BASELINE_LOWER=1` — advertised in the root AGENTS.md as a real
 * escape hatch — could never be reached. The base has to be the commit that
 * PRECEDED the one under test, and only the event knows which that is:
 *
 *   1. `AEGIS_BASE_REF`, when the caller knows the base. ci.yml derives it from
 *      the event (`pull_request.base.sha`, else `before`) and exports it; a human
 *      can set it by hand. `check-android-versioncode.mjs` reads the same variable
 *      for the same reason.
 *   2. `null` in CI with nothing set. The caller must then SKIP the comparison
 *      LOUDLY. Falling back to HEAD here would reintroduce the self-comparison
 *      that reports a pass, which is the one outcome that is worse than not
 *      checking: on the weekly `schedule` run there genuinely is no predecessor
 *      (the push run already covered that commit), and a gate that cannot know
 *      its base must say so rather than invent one.
 *   3. `HEAD` outside CI, which is correct there: the file on disk is the
 *      uncommitted candidate and HEAD is what it would replace.
 *
 * Pure: it reads the given `env` object, never `process.env` itself, so every
 * branch is reachable from a test. `isCI` is likewise a parameter because the
 * caller — not this module — decides what "in CI" means.
 */
export function resolveBaselineBaseRef({ env = {}, isCI = false } = {}) {
  const explicit = env.AEGIS_BASE_REF;
  if (explicit) return { ref: explicit, source: 'AEGIS_BASE_REF' };
  if (isCI) return { ref: null, source: 'ci-without-a-base-ref' };
  return { ref: 'HEAD', source: 'local-HEAD' };
}

/**
 * The operator-facing text for a lowering check that could NOT be made.
 *
 * The two reasons are different failures and read differently, because the fix is
 * different: no base ref means the caller (a workflow) did not supply one, while an
 * unreadable ref means the commit is not in this clone — a `fetch-depth: 0`
 * checkout. Either way the gate ends in the same place — no comparison happened —
 * so both end by saying that a pass is not what this was.
 *
 * This lives in the tested module for the reason `rust-coverage-ratchet.mjs` gives
 * for `formatDeltas`: the ratchets are top-level scripts no test imports, so v8
 * scores them 0% and every line of prose added to one dilutes the very ratio it
 * reports. Here it is also the only way the wording is tested at all.
 */
export function baselineLoweringSkipMessage({ script, base, baselineRel }) {
  const head = `${script}: SKIPPING the "baseline was lowered" check`;
  if (!base || !base.ref) {
    return (
      `\n${head} (${base ? base.source : 'no-base-ref'}).\n` +
      '  A CI run has no base to compare against unless AEGIS_BASE_REF names one;\n' +
      '  without it the only ref available is HEAD, which IS the file just read, so\n' +
      '  the comparison would be a file against itself and would always pass.\n' +
      '  ci.yml derives AEGIS_BASE_REF from the event. This is not a pass.\n'
    );
  }
  return (
    `\n${head}: could not read\n` +
    `  ${baselineRel} at ${base.ref} (${base.source}). Either that commit introduced\n` +
    '  the baseline, or the ref is not in this clone — a checkout with\n' +
    '  fetch-depth: 0 is required for the base commit to be present. Not a pass.\n'
  );
}
